### PR TITLE
Add matches for `/c/*` and `/` in manifest

### PR DESCRIPTION
**Pull request by TaYaKi71751**
#1

### CODE REVIEW

**Review by dannyhines — APPROVED** [review]
This is needed to get the extension to work, looks like OpenAI updated the url of the chat pages
fixes #1

**Comment by guysoft** [comment]
Is there a way to build this extension and test it with the PR?

**Comment by TaYaKi71751** [comment]
> Is there a way to build this extension and test it with the PR?

Probably this would be help
https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/

**Comment by hidao80** [comment]
Thank you, everyone!
I have just released version v0.4 that addresses the URL and DOM tree changes associated with the upgrade of ChatGPT. If you would like, please feel free to use this new version.

Thank you once again!

**Pull request merged**
